REGIONS = {
    "Адыгея": "reg_adygeya",
    "Алтайский край": "reg_altai_krai",
    "Амурская область": "reg_amur_obl",
    "Архангельская область": "reg_arkhangelsk_obl",
    "Астраханская область": "reg_astrakhan_obl",
    "Башкортостан": "reg_bashkortostan",
    "Белгородская область": "reg_belgorod_obl",
    "Брянская область": "reg_bryansk_obl",
    "Бурятия": "reg_buryatia",
    "Владимирская область": "reg_vladimir_obl",
    "Волгоградская область": "reg_volgograd_obl",
    "Вологодская область": "reg_vologda_obl",
    "Воронежская область": "reg_voronezh_obl",
    "Дагестан": "reg_dagestan",
    "Еврейская АО": "reg_eao",
    "Забайкальский край": "reg_zabaykalsk_krai",
    "Ивановская область": "reg_ivanovo_obl",
    "Ингушетия": "reg_ingushetia",
    "Иркутская область": "reg_irkutsk_obl",
    "Кабардино-Балкария": "reg_kabardino_balkaria",
    "Калининградская область": "reg_kaliningrad_obl",
    "Калмыкия": "reg_kalmykia",
    "Калужская область": "reg_kaluga_obl",
    "Камчатский край": "reg_kamchatka_krai",
    "Карачаево-Черкесия": "reg_karachay_cherkessia",
    "Карелия": "reg_karelia",
    "Кемеровская область": "reg_kemerovo_obl",
    "Кировская область": "reg_kirov_obl",
    "Коми": "reg_komi",
    "Костромская область": "reg_kostroma_obl",
    "Краснодарский край": "reg_krasnodar_krai",
    "Красноярский край": "reg_krasnoyarsk_krai",
    "Курганская область": "reg_kurgan_obl",
    "Курская область": "reg_kursk_obl",
    "Ленинградская область": "reg_leningrad_obl",
    "Липецкая область": "reg_lipetsk_obl",
    "Магаданская область": "reg_magadan_obl",
    "Марий Эл": "reg_mari_el",
    "Мордовия": "reg_mordovia",
    "Москва": "reg_moscow",
    "Московская область": "reg_moscow_obl",
    "Мурманская область": "reg_murmansk_obl",
    "Ненецкий АО": "reg_nenets_ao",
    "Нижегородская область": "reg_nizhny_novgorod_obl",
    "Новгородская область": "reg_novgorod_obl",
    "Новосибирская область": "reg_novosibirsk_obl",
    "Омская область": "reg_omsk_obl",
    "Оренбургская область": "reg_orenburg_obl",
    "Орловская область": "reg_orlov_obl",
    "Пензенская область": "reg_penza_obl",
    "Пермский край": "reg_perm_krai",
    "Приморский край": "reg_primorsky_krai",
    "Псковская область": "reg_pskov_obl",
    "Ростовская область": "reg_rostov_obl",
    "Рязанская область": "reg_ryazan_obl",
    "Самарская область": "reg_samara_obl",
    "Санкт-Петербург": "reg_saint_petersburg",
    "Саратовская область": "reg_saratov_obl",
    "Саха (Якутия)": "reg_sakha_yakutia",
    "Сахалинская область": "reg_sakhalin_obl",
    "Свердловская область": "reg_sverdlovsk_obl",
    "Северная Осетия": "reg_north_ossetia",
    "Смоленская область": "reg_smolensk_obl",
    "Ставропольский край": "reg_stavropol_krai",
    "Тамбовская область": "reg_tambov_obl",
    "Татарстан": "reg_tatarstan",
    "Тверская область": "reg_tver_obl",
    "Томская область": "reg_tomsk_obl",
    "Тульская область": "reg_tula_obl",
    "Тува": "reg_tuva",
    "Тюменская область": "reg_tyumen_obl",
    "Удмуртия": "reg_udmurtia",
    "Ульяновская область": "reg_ulyanovsk_obl",
    "Хабаровский край": "reg_khabarovsk_krai",
    "Хакасия": "reg_khakassia",
    "Ханты-Мансийский АО": "reg_khanty_mansi_ao",
    "Челябинская область": "reg_chelyabinsk_obl",
    "Чеченская Республика": "reg_chechnya",
    "Чувашия": "reg_chuvashia",
    "Чукотский АО": "reg_chukotka_ao",
    "Ямало-Ненецкий АО": "reg_yamalo_nenets_ao",
    "Ярославская область": "reg_yaroslavl_obl"
}
